export const config = {
  chainId: import.meta.env.VITE_ALPHA_CHAIN_ID || 'alpha-1',
  chainName: import.meta.env.VITE_ALPHA_CHAIN_NAME || 'Alpha Local',
  rpcUrl: import.meta.env.VITE_ALPHA_RPC_URL || '/alpha-rpc',
  restUrl: import.meta.env.VITE_ALPHA_REST_URL || '/alpha-rest',
  apiUrl: import.meta.env.VITE_MIDDLEWARE_API_URL || '/api',
  prefix: import.meta.env.VITE_ALPHA_PREFIX || 'cosmos',
  transferDenom: import.meta.env.VITE_ALPHA_TRANSFER_DENOM || 'token',
  feeDenom: import.meta.env.VITE_ALPHA_FEE_DENOM || 'stake',
  coinType: Number(import.meta.env.VITE_ALPHA_COIN_TYPE || '118'),
  coinDecimals: Number(import.meta.env.VITE_ALPHA_COIN_DECIMALS || '0'),
  keycloakUrl: import.meta.env.VITE_KEYCLOAK_URL || 'http://127.0.0.1:18080',
  keycloakRealm: import.meta.env.VITE_KEYCLOAK_REALM || 'alpha',
  keycloakClientId: import.meta.env.VITE_KEYCLOAK_CLIENT_ID || 'authz-console',
} as const
